#!/usr/bin/env bash
# Configures nginx with my server ip and a return string
apt-get update
apt-get -y install nginx

#Creating new configuration for Nginx
server {
        listen 80;
        listen [::]:80;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name 100.27.0.213;

        location / {
                return 200 "Hello World!\n";
        }
}

# Enabling the new configuration
ln -s /etc/nginx/sites-available/1-install_nginx_web_server /etc/nginx/sites-enabled/

# Restarting Nginx to applyy changes
service nginx restart
