#!/usr/bin/env bash
# Configures nginx with my server ip and a return string

#Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

#Assigning ownership of root directory to User
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backing up default nginx index for safe keeping
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backup

#Modifying index with new output string
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Backing up a default config file for contingency
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

#Configuring Nginx for to redirect redirect_me
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location / {
                try_files $uri $uri/ =404;
        }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

new_string="\\\t\trewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"                                sudo sed -i "7i $new_string" /etc/nginx/sites-available/default

# Restarting Nginx to apply changes
sudo systemctl restart nginx
