#!/usr/bin/env bash
#This script displays numbers from 1 to 100. It displays FizzBuzz when the number is a multiple of 3 and 5, displays Fizz when the number a multiple of  3, and Buzz when the numer is is a multiple of 5.


counter=1
while ((counter <= 100))
do
	if ((counter % 3 == 0)) && ((counter % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((counter % 3 == 0))
	then
		echo "Fizz"
	elif ((counter % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$counter"
	fi

	((counter++))
done
