#!/usr/bin/env bash
# This script uses a while loop to display number drom 1 to 20. It displays 4 and then bad luck from China for the 4th loop, 9 and then bad luck from Japan for the 9th loop, and 17 and then bad luck from Italy on the 17th loop.


counter=1
while ((counter <= 20))
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac

	((counter++))
done		
