#!/usr/bin/env bash
This bash script lists the content of the current directory in a list format. For each file display only the part of the name after the first dash.


files=$(ls)
for file in $files
do
	echo "$file" | cut -d"-" -f2
done
