#!/usr/bin/env bash
#This bash script lists the content of the current directory in a list format. For each file display only the part of the name after the first dash.


for file in *
do
	if [ -f "$file" ]
	then
		cut_separator=$(echo "$file" | cut -d"-" -f2)
		echo "$cut_separator"
	fi
done
