#!/usr/bin/env bash
#This scriptgives information about the school file. It checks if the file exists and that if it's a regular file and if it's empty.


directory="$PWD"
school_file="$directory/school"

if [ -e "$school_file" ]
then
	echo "school file exists"

	if [ -f "$school_file" ]
	then
		echo "school file is a regular file"

		if [ -s "$school_file" ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"

		fi
	fi

else
	echo "school file does not exist"

fi
